services:
  - docker

before_install:
  - docker build -t cooperwalter/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cooperwalter/react-test npm test

after_success:
  - docker build -t cooperwalter/multi-client ./client
  - docker build -t cooperwalter/multi-nginx ./nginx
  - docker build -t cooperwalter/multi-server ./server
  - docker build -t cooperwalter/multi-worker ./worker
  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push cooperwalter/multi-client
  - docker push cooperwalter/multi-nginx
  - docker push cooperwalter/multi-server
  - docker push cooperwalter/multi-worker