version: 2.1
jobs:
  test:
      working_directory: /app
      docker:
        - image: docker:17.05.0-ce-git
      steps:
        - run: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            
workflows:
  test-workflow:
    jobs:
      - test