version: 2.1
jobs:
  test:
      working_directory: /app
      docker:
        - image: docker:20.10.14-git
      steps:
        - checkout
        - setup_remote_docker
        - run: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
        - run: |
            docker run -e CI=true cooperwalter/react-test npm test
workflows:
  test-workflow:
    jobs:
      - test